src/Entity/Person.php
<?php

/*
 * This file is part of the Jedisjeux project.
 *
 * (c) Jedisjeux
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as JMS;
use Knp\DoctrineBehaviors\Model\Timestampable\Timestampable;
use Sylius\Component\Product\Model\ProductInterface;
use Sylius\Component\Resource\Model\ResourceInterface;
use Sylius\Component\Taxonomy\Model\TaxonInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Person.
 *
 * @ORM\Entity
 * @ORM\Table(name="jdj_person", indexes={@ORM\Index(name="search_idx", columns={"slug"})})
 *
 * @JMS\ExclusionPolicy("all")
 */
class Person implements ResourceInterface
{
    use IdentifiableTrait,
        Timestampable;

    /**
     * @var string
     *
     * @ORM\Column(type="string", unique=true)
     *
     * @JMS\Expose
     * @JMS\Groups({"Default"})
     */
    protected $code;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50)
     *
     * @Assert\NotBlank()
     *
     * @JMS\Expose
     * @JMS\Groups({"Default", "Detailed"})
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50, nullable=true)
     *
     * @JMS\Expose
     * @JMS\Groups({"Default", "Detailed"})
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=200, nullable=true)
     *
     * @JMS\Expose
     * @JMS\Groups({"Detailed"})
     */
    private $website;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     *
     * @JMS\Expose
     * @JMS\Groups({"Detailed"})
     */
    private $description;

    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"firstName","lastName"}, separator="-")
     * @ORM\Column(type="string", length=128, unique=true)
     *
     * @JMS\Expose
     * @JMS\Groups({"Default", "Detailed"})
     */
    private $slug;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $productCount = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $productCountAsDesigner = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $productCountAsArtist = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $productCountAsPublisher = 0;

    /**
     * @var PersonImage[]|Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\PersonImage", mappedBy="person", cascade={"persist", "merge", "remove"})
     */
    protected $images;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Sylius\Component\Taxonomy\Model\TaxonInterface")
     * @ORM\JoinTable("jdj_person_taxon",
     *      inverseJoinColumns={@ORM\JoinColumn(name="taxoninterface_id", referencedColumnName="id")}
     * )
     */
    protected $taxons;

    /**
     * @var ProductInterface[]|Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\ProductVariant", mappedBy="designers", cascade={"persist", "merge"})
     */
    private $designerProducts;

    /**
     * @var ProductInterface[]|Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\ProductVariant", mappedBy="artists", cascade={"persist", "merge"})
     */
    private $artistProducts;

    /**
     * @var ProductInterface[]|Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\ProductVariant", mappedBy="publishers", cascade={"persist", "merge"})
     */
    private $publisherProducts;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->designerProducts = new ArrayCollection();
        $this->artistProducts = new ArrayCollection();
        $this->publisherProducts = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->taxons = new ArrayCollection();
        $this->code = uniqid('person_');
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * @return PersonImage
     *
     * @deprecated
     */
    public function getMainImage()
    {
        return $this->getFirstImage();
    }

    /**
     * @return PersonImage
     *
     * @JMS\VirtualProperty
     * @JMS\SerializedName("image")
     * @JMS\Groups({"Default", "Detailed"})
     */
    public function getFirstImage(): ?PersonImage
    {
        $firstImage = $this->images->first();

        return false !== $firstImage ? $firstImage : null;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * @return ProductInterface[]|Collection
     */
    public function getPublisherProducts(): Collection
    {
        return $this->publisherProducts;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): void
    {
        $this->website = $website;
    }

    /**
     * @return ProductInterface[]|Collection
     */
    public function getDesignerProducts(): Collection
    {
        return $this->designerProducts;
    }

    /**
     * @return ProductInterface[]|Collection
     */
    public function getArtistProducts(): Collection
    {
        return $this->artistProducts;
    }

    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setSlug(?string $slug): void
    {
        $this->slug = $slug;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getProductCount(): int
    {
        return $this->productCount;
    }

    public function setProductCount(int $productCount): void
    {
        $this->productCount = $productCount;
    }

    public function getProductCountAsDesigner(): int
    {
        return $this->productCountAsDesigner;
    }

    public function setProductCountAsDesigner(int $productCountAsDesigner): void
    {
        $this->productCountAsDesigner = $productCountAsDesigner;
    }

    public function getProductCountAsArtist(): int
    {
        return $this->productCountAsArtist;
    }

    public function setProductCountAsArtist(int $productCountAsArtist): void
    {
        $this->productCountAsArtist = $productCountAsArtist;
    }

    public function getProductCountAsPublisher(): int
    {
        return $this->productCountAsPublisher;
    }

    public function setProductCountAsPublisher(int $productCountAsPublisher): void
    {
        $this->productCountAsPublisher = $productCountAsPublisher;
    }

    /**
     * @return PersonImage[]|Collection
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function hasImage(PersonImage $image): bool
    {
        return $this->images->contains($image);
    }

    public function addImage(PersonImage $image): void
    {
        if (!$this->hasImage($image)) {
            $image->setPerson($this);
            $this->images->add($image);
        }
    }

    public function removeImage(PersonImage $image): void
    {
        $this->images->removeElement($image);
    }

    /**
     * @param null|string $rootTaxon
     *
     * @return Collection|\Sylius\Component\Taxonomy\Model\TaxonInterface[]
     */
    public function getTaxons($rootTaxon = null): Collection
    {
        if (null !== $rootTaxon) {
            return $this->taxons->filter(function (TaxonInterface $taxon) use ($rootTaxon) {
                return $rootTaxon === strtolower($taxon->getRoot()->getCode());
            });
        }

        return $this->taxons;
    }

    public function getZone(): ?TaxonInterface
    {
        $zones = $this->getTaxons('zones');

        return $zones->count() > 0 ? $zones->first() : null;
    }

    public function setZone(TaxonInterface $zone): void
    {
        if ($this->getZone()) {
            $this->removeTaxon($this->getZone());
        }

        $this->addTaxon($zone);
    }

    public function hasTaxon(TaxonInterface $taxon): bool
    {
        return $this->taxons->contains($taxon);
    }

    public function addTaxon(TaxonInterface $taxon): void
    {
        if (!$this->hasTaxon($taxon)) {
            $this->taxons->add($taxon);
        }
    }

    public function removeTaxon(TaxonInterface $taxon): void
    {
        $this->taxons->removeElement($taxon);
    }

    /**
     * @JMS\VirtualProperty
     * @JMS\SerializedName("full_name")
     * @JMS\Groups({"Default", "Detailed", "Autocomplete"})
     */
    public function getFullName(): string
    {
        if (null === $this->getFirstName()) {
            return $this->getLastName();
        }

        return $this->getFirstName().' '.$this->getLastName();
    }

    /**
     * Convert Entity To String.
     */
    public function __toString(): string
    {
        return $this->getFullName();
    }
}

src/Form/Type/PersonType.php
<?php

/*
 * This file is part of the Jedisjeux project.
 *
 * (c) Jedisjeux
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Type;

use App\Entity\Taxon;
use Doctrine\ORM\EntityRepository;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * @author Loïc Frémont <loic@mobizel.com>
 */
class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastName', null, [
                'label' => 'sylius.ui.last_name',
            ])
            ->add('firstName', null, [
                'label' => 'sylius.ui.first_name',
                'required' => false,
            ])
            ->add('zone', EntityType::class, [
                'label' => 'label.zone',
                'class' => 'App:Taxon',
                'group_by' => 'parent',
                'choice_label' => 'name',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('o')
                        ->join('o.root', 'rootTaxon')
                        ->where('rootTaxon.code = :code')
                        ->andWhere('o.parent IS NOT NULL')
                        ->setParameter('code', Taxon::CODE_ZONE)
                        ->orderBy('o.left');
                },
                'expanded' => false,
                'multiple' => false,
                'placeholder' => 'Choisissez une zone',
                'required' => false,
            ])
            ->add('website', null, [
                'label' => 'label.website',
                'required' => false,
            ])
            ->add('description', CKEditorType::class, [
                'label' => 'label.description',
                'required' => false,
            ])
            ->add('images', CollectionType::class, [
                'entry_type' => PersonImageType::class,
                'label' => 'sylius.ui.images',
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'required' => false,
            ])

        ;
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'app_person';
    }
}

src/Controller/PersonController.php
<?php

/*
 * This file is part of the Jedisjeux project.
 *
 * (c) Jedisjeux
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Repository\PersonRepository;
use Doctrine\ORM\EntityRepository;
use FOS\RestBundle\View\View;
use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Sylius\Component\Resource\ResourceActions;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class PersonController extends ResourceController
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexWithTaxonsAction(Request $request)
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);
        $this->isGrantedOr403($configuration, ResourceActions::INDEX);

        $rootTaxon = $this->getTaxonRepository()->findOneBy(['code' => ['zones']]);

        $resources = $this->resourcesCollectionProvider->get($configuration, $this->repository);

        $view = View::create($resources);

        if ($configuration->isHtmlRequest()) {
            $view
                ->setTemplate($configuration->getTemplate(ResourceActions::INDEX))
                ->setTemplateVar($this->metadata->getPluralName())
                ->setData([
                    'rootTaxon' => $rootTaxon,
                    'metadata' => $this->metadata,
                    'resources' => $resources,
                    $this->metadata->getPluralName() => $resources,
                ])
            ;
        }

        return $this->viewHandler->handle($configuration, $view);
    }

    /**
     * @param string $slug
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexByTaxonAction(Request $request, $slug)
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);
        $this->isGrantedOr403($configuration, ResourceActions::INDEX);

        $taxon = $this->get('sylius.repository.taxon')->findOneBySlug($slug, $this->getParameter('locale'));
        if (!isset($taxon)) {
            throw new NotFoundHttpException('Requested taxon does not exist.');
        }

        $rootTaxon = $this->getTaxonRepository()->findOneBy(['code' => ['zones']]);

        /** @var PersonRepository $repository */
        $repository = $this->repository;

        $resources = $this->resourcesCollectionProvider->get($configuration, $this->repository);

        $view = View::create($resources);

        if ($configuration->isHtmlRequest()) {
            $view
                ->setTemplate($configuration->getTemplate('indexByTaxon.html'))
                ->setTemplateVar($this->metadata->getPluralName())
                ->setData([
                    'metadata' => $this->metadata,
                    'taxon' => $taxon,
                    'rootTaxon' => $rootTaxon,
                    'resources' => $resources,
                    $this->metadata->getPluralName() => $resources,
                ]);
        }

        return $this->viewHandler->handle($configuration, $view);
    }

    /**
     * @return EntityRepository
     */
    protected function getTaxonRepository()
    {
        return $this->get('sylius.repository.taxon');
    }
}

templates/frontend/person/_single.html.twig
{% import 'macro/image.html.twig' as images %}

{% set personPath = path('app_frontend_person_show', { 'slug': person.slug }) %}
{% set imagePath =  person.mainImage is not null ? person.mainImage.webPath : '/assets/frontend/images/placeholder.png' %}

<div class="image-box style-2 mb-20 bordered light-gray-bg">
    <div class="overlay-container overlay-visible">
        {{ images.render(imagePath, 'magazine_item', person) }}
        <a class="overlay-link" href="{{ personPath }}"><i class="fa fa-link"></i></a>
        <div class="overlay-bottom text-left">
            <p class="lead margin-clear">{{ person }}</p>
        </div>
    </div>
    <div class="body text-center">
        <ul class="list-icons mb-10 small">
            {% if person.productCountAsDesigner > 0 %}
                <li><i class="fa fa-cogs"></i> Auteur de {{ person.productCountAsDesigner }} jeux</li>
            {% endif %}
            {% if person.productCountAsArtist > 0 %}
                <li><i class="fa fa-paint-brush"></i> Illustrateur de {{ person.productCountAsArtist }} jeux</li>
            {% endif %}
            {% if person.productCountAsPublisher > 0 %}
                <li><i class="fa fa-upload"></i> Éditeur de {{ person.productCountAsPublisher }} jeux</li>
            {% endif %}
        </ul>
        <a href="{{ personPath }}" class="btn btn-default btn-sm margin-clear">{{ 'sylius.ui.view_more'|trans }}<i class="fa fa-arrow-right pl-10"></i></a>
    </div>
</div>

templates/frontend/person/index.html.twig
{% extends 'frontend/layout.html.twig' %}

{% from 'macro/pagination.html.twig' import simple as pagination %}

{% set pageTitle %}
    {{ 'app.ui.ludographies'|trans }}
{% endset %}

{% block content %}
    {% include 'frontend/person/index/_banner.html.twig' %}

    <!-- main-container start -->
    <!-- ================ -->
    <section class="main-container">
        <div class="container">
            <div class="row">
                <!-- main start -->
                <!-- ================ -->
                <div id="people-list" class="main col-12">
                    <div class="row grid-space-10">
                        {% for person in people.data %}
                            <div class="col-md-6 col-lg-3">
                                {% include 'frontend/person/_single.html.twig' %}
                            </div>
                        {% endfor %}
                    </div>

                    <!-- pagination start -->
                    {{ pagination(people.data) }}
                    <!-- pagination end -->

                </div>
                <!-- main end -->
            </div>
        </div>
    </section>
    <!-- main-container end -->

    {% include 'frontend/person/index/_footerTop.html.twig' %}
{% endblock content %}

templates/frontend/person/indexByZone.html.twig
{% extends 'frontend/layout.html.twig' %}

{% from 'macro/pagination.html.twig' import simple as pagination %}

{% block content %}
    {% include 'frontend/person/indexByZone/_banner.html.twig' %}

    <!-- main-container start -->
    <!-- ================ -->
    <section class="main-container">
        <div class="container">
            <div class="row">
                <!-- main start -->
                <!-- ================ -->
                <div id="people-list" class="main col-12">
                    <div class="row grid-space-10">
                        {% for person in people.data %}
                            <div class="col-md-6 col-lg-3">
                                {% include 'frontend/person/_single.html.twig' %}
                            </div>
                        {% endfor %}
                    </div>

                    <!-- pagination start -->
                    {{ pagination(people.data) }}
                    <!-- pagination end -->

                </div>
                <!-- main end -->
            </div>
        </div>
    </section>
    <!-- main-container end -->

    {% include 'frontend/person/index/_footerTop.html.twig' %}
{% endblock content %}

templates/frontend/person/show.html.twig
{% extends 'frontend/layout.html.twig' %}

{% set pageTitle %}
    {{ person.fullName }}
{% endset %}

{% block content %}
    {% include 'frontend/person/show/_breadcrumb.html.twig' %}

    <!-- main-container start -->
    <!-- ================ -->
    <section class="main-container">

        <div class="container">
            <div class="row">

                <!-- main start -->
                <!-- ================ -->
                <div class="main col-12">

                    <!-- page-title start -->
                    <!-- ================ -->
                    <h1 class="page-title text-center">{{ person }}</h1>
                    <p class="large text-center">{{ person.zone }}</p>
                    <div class="separator with-icon"><i class="fa fa-user bordered"></i></div>
                    <!-- page-title end -->

                    <div class="row">
                        <div class="col-lg-4 col-xl-5">
                            <!-- pills start -->
                            <!-- ================ -->
                            <!-- Nav tabs -->
                            <ul class="nav nav-pills">
                                <li class="nav-item"><a class="nav-link active" href="#pill-1" data-toggle="tab" title="images"><i class="fa fa-camera pr-1"></i> Photo</a></li>
                                <li class="nav-item"><a class="nav-link" href="#pill-2" data-toggle="tab" title="video"><i class="fa fa-video-camera pr-1"></i> Video</a></li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content clear-style">
                                <div class="tab-pane active" id="pill-1">
                                    {% include 'frontend/person/show/_images.html.twig' %}
                                </div>
                                <div class="tab-pane" id="pill-2">
                                    <div class="overlay-container">
                                        <img src="/assets/frontend/images/page-about-2.jpg" alt="">
                                        <a class="overlay-link" href="#"><i class="fa fa-link"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!-- pills end -->
                        </div>
                        <div class="col-lg-8 col-xl-7 pv-30">
                            <h2 class="mt-4">Présentation</h2>
                            {{ person.description|raw }}
                            {% include 'frontend/person/show/_specifications.html.twig' %}
                        </div>
                    </div>
                </div>
                <!-- main end -->

            </div>
        </div>
    </section>
    <!-- main-container end -->

    <!-- section start -->
    <!-- ================ -->
    <section class="pv-30 light-gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    {% include 'frontend/person/show/_reviews.html.twig' %}
                    <!-- comments end -->
                </div>

                {% include 'frontend/person/show/_sidebar.html.twig' %}

            </div>
        </div>
    </section>
    <!-- section end -->

    {% include 'frontend/footer/_top.html.twig' %}
{% endblock content %}